server:
  port: 8888
spring:
  kafka:
    bootstrap-servers: 193.112.111.196:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-commit-interval: 100
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: xry-consumer-group
#  data:
#    mongodb:
#      database: gg
#      username: gg
#      password: gg123
#      host: 193.112.111.196
#      port: 27017


mongodb:
  mmProperties:
      database: mm
      username: mm
      password: mm123
      host: 193.112.111.196
      port: 27017
  ggProperties:
      database: gg
      username: gg
      password: gg123
      host: 193.112.111.196
      port: 27017